### ISSUE TITLE
Shouldn't '-error-.invalid' be invalid domain?

### ISSUE THREAD

**Issue by pawelkg** [thephpleague/uri-components#26] opened 2019-10-24 10:10 UTC
|    Q        |   A
|------------ | ------
| Version     | 2.0.0

### Question
This code:
```php
$uri = Uri::createFromString('http://-error-.invalid/');
$host = Host::createFromUri($uri);
var_dump($host->isDomain());
```
Results in true, while '-error-.invalid' is not valid domain name as far as I know. I can not find any reference do RFC or something similar. But In Wikipedia article about 'Domain name' there is: "A domain name consists of one or more labels, each of which is formed from the set of ASCII letters, digits, and hyphens (a-z, A-Z, 0-9, -), but not starting or ending with a hyphen." (see: https://en.wikipedia.org/wiki/Domain_name#Technical_requirements_and_process).
I see that REGEXP_DOMAIN_NAME (in Host.php file) is reference to host part in URI rather to domain name itself.

**Comment by nyamsprod** [comment] 2019-10-24 14:35
I've made a patch for this if I have time I'll make a PR out of it before the weekend

**Comment by nyamsprod** [comment] 2019-11-04 15:02
the issue is resolved in the master branch and a new patch release will be release later this week.

**Closed by nyamsprod** 2019-11-04 15:02 UTC
Labels: bug, version 2.0
